// controllers/user_controller.js
import crypto from 'crypto';
import { User } from '../models/user_model.js';
import { send_password_reset_email } from '../utils/email.js'; 


/*
This code uses the pbkdf2Sync function to hash the password with a salt. 
The salt is a random string generated by crypto.randomBytes. The 1000 is the number of iterations,
64 is the key length, and sha512 is the digest algorithm. Adjust these values as needed for your application.
*/




/*
1. Benutzer fordert das Zurücksetzen des Passworts an: Der Benutzer gibt seine E-Mail-Adresse ein, und 
Ihre Anwendung sendet ihm eine E-Mail mit einem eindeutigen Link zum Zurücksetzen des Passworts.

2. Generierung des Tokens für das Zurücksetzen des Passworts: Ihre Anwendung generiert einen eindeutigen Token, 
speichert ihn im Datensatz des Benutzers in der Datenbank und fügt ihn in den Link zum Zurücksetzen des Passworts ein.

3. Benutzer setzt das Passwort zurück: Der Benutzer klickt auf den Link, gelangt zur Seite für das Zurücksetzen des Passworts,
gibt ein neues Passwort ein und sendet das Formular ab. Ihre Anwendung überprüft den Token, findet den entsprechenden
Benutzer und aktualisiert sein Passwort. 
*/


export const request_password_reset = async (req, res) => {
  const { email } = req.body;

  try {
    const user = await User.findOne({ where: { email } });

    if (!user) {
      return res.status(400).send({ error: 'No user found with that email' });
    }

    const token = crypto.randomBytes(20).toString('hex');
    const expires = new Date();
    expires.setHours(expires.getHours() + 1);  // Token expires in 1 hour

    user.password_reset_token = token;
    user.password_reset_expires = expires;

    await user.save();

    await send_password_reset_email(email, token);

    res.send({ message: 'Password reset email sent' });
  } catch (error) {
    res.status(400).send({ error: 'Error resetting password' });
  }
};

export const reset_password = async (req, res) => {
  const { token } = req.params;
  const { password } = req.body;

  // Validate the new password
  if (password.length < 8) {
    return res.status(400).send({ error: 'Password must be at least 8 characters' });
  }

  try {
    const user = await User.findOne({ where: { password_reset_token: token } });

    if (!user) {
      return res.status(400).send({ error: 'Invalid password reset token' });
    }

    if (user.password_reset_expires < new Date()) {
      return res.status(400).send({ error: 'Expired password reset token' });
    }

    // Hash the new password
    const salt = crypto.randomBytes(16).toString('hex');
    const hashedPassword = crypto.pbkdf2Sync(password, salt, 1000, 64, `sha512`).toString(`hex`);

    user.password = hashedPassword;
    user.password_reset_token = null;
    user.password_reset_expires = null;

    await user.save();

    res.send({ message: 'Password reset successfully' });
  } catch (error) {
    res.status(400).send({ error: 'Error resetting password' });
  }
};